kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: a-simple-pipeline
spec:
  params:
  - name: username
  - name: wife
  tasks:
  - name: task-1
    params:
    - name: username
      value: $(params.username)
    taskSpec:
      params:
      - name: username
      steps:
      - image: alpine:3.15
        script: |
          echo "hello $(params.username)"
  - name: task-2
    params:
    - name: wife
      value: $(params.wife)
    taskSpec:
      params:
      - name: wife
      steps:
      - image: alpine:3.15
        script: |
          echo "hello $(params.wife)"